# Generated by Django 2.1.1 on 2018-09-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_business_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostToApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Application')),
                ('hobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Host')),
            ],
        ),
    ]
