# Generated by Django 2.1.1 on 2018-09-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uptime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=60, null=True)),
                ('test', models.EmailField(error_messages={'invalid': '请输入密码'}, max_length=19, null=True)),
                ('user_type_id', models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, '普普通用户')], default=1)),
                ('user_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup')),
            ],
        ),
    ]
